### ISSUE TITLE
english man

### ISSUE THREAD

**Issue by 16pxdesign** [davidecesarano/Validation#3]

**Comment by jackttcoms** [comment]
👍

**Comment by davidecesarano** [comment]
Hi!
I am italian man, but if you want english man try [Embryo Validation](https://github.com/davidecesarano/Embryo-Validation), the new version of this repository 😛

**Comment by jackttcoms** [comment]
No worries. I know Italian. Just takes longer for me to translate in the brain. Amazing class. Thanks
