### ISSUE TITLE
not true for false:boolean values

### ISSUE THREAD

**Issue by JaneMax** [davidecesarano/Validation#4]
https://github.com/davidecesarano/Validation/blob/483011fe6b667b790fcd07b328f1af3f4b44bb3a/Validation.php#L375
that is  right: if( is_bool(filter_var($value, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE))) return true;
in your case the $value = false will nothing return, but it is boolean.

**Comment by davidecesarano** [comment]
Hi @JaneMax ,
you're right!
Fix it in new commit.

Thank's.
